// Testing jenkinsfile...
// This file should be in root folder or path must be specified in jenkins configurations to be detected.

pipeline { 
    agent any 
    stages { 
        stage("build") { 
            when {
                expression {
                    BRANCH_NAME == 'master'
                }
            }
            steps {
                echo 'Building the application...' 
            }
        } 
        stage("test") { 
            when {
                expression {
                    BRANCH_NAME == 'develop'
                }
            }
            steps {
                echo 'Testing the application...'
            }
        } 
        stage("deploy") { 
            steps {
                echo 'Deploying the application...'
            }
        }
    }  
}